import "./globals.css";
import type { Metadata } from "next";
// import { Noto_Sans_JP } from "next/font/google";
import { AuthContextProvider } from "./context/AuthContext";
import { ChannelContextProvider } from "./context/ChannelContext";

// const notojp = Noto_Sans_JP({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--noto-sans-jp",
// });

export const metadata: Metadata = {
  title: "STC2023 Discord Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ fontFamily: `var(--noto-sans-jp)` }}>
        <AuthContextProvider>
          <ChannelContextProvider>{children}</ChannelContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
